<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <sitemap>
      <loc>http://tnris.org/sitemap-main.xml</loc>
      <lastmod>{{ modified_date | date('Y-m-d') }}</lastmod>
   </sitemap>
   <sitemap>
      <loc>http://tnris.org/sitemap-datadownload.xml</loc>
      <lastmod>{{ modified_date | date('Y-m-d') }}</lastmod>
   </sitemap>
</sitemapindex>
